### PR TITLE
10.1.1 Update

### PR DESCRIPTION
**Pull request by voroyam**
Updated oC to 10.1.1 and onlyoffice to 2.1.7 with corresponding checksum.

### CODE REVIEW

**Comment by tboerger** [comment]
No changelog? :)

**Comment by voroyam** [comment]
should I always write a change log in the PR?

**Comment by tboerger** [comment]
Let's skip that for now, but we should add that for the previous changes as well.

**Comment by voroyam** [comment]
Okay, noted.

**Pull request merged**
